# serviceswiagentd.yml

- name: Restart swiagentd service
  hosts: all # Replace 'your_server' with the target server or group of servers where swiagentd service is running
  become: yes

  tasks:
    - name: Restart swiagentd service using shell command
      shell: sudo systemctl status swiagentd
      
    - name: Restart swiagentd service using shell command
      shell: sudo systemctl restart swiagentd