# The playbook consists of three tasks:

# The first task uses the apt module to update the APT package cache.
# The second task uses the apt module to perform a distribution upgrade, effectively updating all packages to the latest versions.
# The final task displays a summary of the updates performed.

---
- name: Update Ubuntu Servers
  hosts: all
  become: yes  # To run commands with sudo (root) privileges

  tasks:
    - name: Update APT package cache
      shell: sudo apt-get update
      register: update_cache_result

    - name: Display APT cache update summary
      debug:
        var: update_cache_result.stdout_lines

    - name: Upgrade all packages on servers
      shell: sudo apt-get upgrade -y
      register: upgrade_result

    - name: Display package upgrade summary
      debug:
        var: upgrade_result.stdout_lines
    

