- name: Update Ubuntu Servers
  hosts: all
  become: yes

  tasks:
  - name: Update APT package cache
    shell: apt-get update
    register: update_cache_result

  - name: Display APT cache update summary
    debug:
      var: update_cache_result.stdout_lines

  - name: Upgrade all packages on servers
    shell: apt-get upgrade -y
    register: upgrade_result

  - name: Display package upgrade summary
    debug:
      var: upgrade_result.stdout_lines

  - name: Reboot if required
    reboot:
    when: "'System restart required' in upgrade_result.stdout"
